import { createContext, useContext, useState } from 'react';

type Language = 'ar' | 'fr';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  ar: {
    home: "الرئيسية",
    dashboard: "لوحة التحكم",
    pendingRequests: "الطلبات المعلقة",
    approvedRequests: "الطلبات الموافق عليها",
    vacationDays: "أيام الإجازة",
    awaitingApproval: "في انتظار الموافقة",
    thisMonth: "هذا الشهر",
    remaining: "متبقية",
    workCertificate: "طلب شهادة عمل",
    missionOrder: "أمر مهمة",
    vacationRequest: "طلب إجازة",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
    logout: "تسجيل الخروج",
    search: "بحث",
    viewAll: "عرض الكل",
    name: "الاسم",
    startDate: "تاريخ البداية",
    endDate: "تاريخ النهاية",
    submit:" إرسال الطلب",
    cancel: "إلغاء",
    signatureUpload: "رفع التوقيع",
    reason: "السبب",
    type: "النوع",
    description: "الوصف",
    save: "حفظ",
    requestType: "نوع الطلب",
    workCertificateTitle: "طلب شهادة عمل",
    missionOrderTitle: "طلب أمر مهمة",
    vacationRequestTitle: "طلب إجازة",
    purposeLabel: "الغرض من الطلب",
    purposePlaceholder: "على سبيل المثال: تقديم للبنك، تأشيرة سفر، إلخ",
    additionalInfo: "معلومات إضافية",
    additionalInfoPlaceholder: "أي معلومات إضافية ترغب في إضافتها للطلب",
    signatureUploadButton: "اختر ملف التوقيع",
    requestSubmitted: "تم تقديم طلبك بنجاح!",
    requestReviewMessage: "سيتم مراجعة الطلب وإصدار الشهادة في أقرب وقت",
    followUpMessage: "يمكنك متابعة حالة الطلب من الصفحة الرئيسية",
    newRequest: "طلب جديد",
    requestInfo: "معلومات الطلب",
    destination: "الوجهة",
    destinationPlaceholder: "على سبيل المثال: الداربيضاء، الرباط، خارج البلاد",
    selectDate: "اختر تاريخ",
    signature: "التوقيع",
    annualLeave: "إجازة سنوية",
    sickLeave: "إجازة مرضية",
    emergencyLeave: "إجازة اضطرارية",
    unpaidLeave: "إجازة بدون راتب",
    vacationReasonPlaceholder: "يرجى ذكر سبب الإجازة إذا كان ذلك ضرورياً",
    profileSettings: "معلومات الملف الشخصي",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    saveChanges: "حفظ التغييرات",
    notificationSettings: "إعدادات الإشعارات",
    emailNotifications: "إشعارات البريد الإلكتروني",
    emailNotificationsDesc: "استلام الإشعارات عبر البريد الإلكتروني",
    newRequests: "طلبات جديدة",
    newRequestsDesc: "إشعارات عند إنشاء طلبات جديدة",
    requestUpdates: "تحديثات الطلبات",
    requestUpdatesDesc: "إشعارات عند تحديث حالة الطلبات",
    passwordSettings: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    changePassword: "تغيير كلمة المرور",
    profileTab: "الملف الشخصي",
    notificationsTab: "الإشعارات",
    passwordTab: "كلمة المرور",
    urgentChat: "محادثة عاجلة",
    urgentMessageTitle: "رسالة عاجلة للإدارة",
    urgentMessagePlaceholder: "اكتب رسالتك العاجلة هنا...",
    urgentMessageSend: "إرسال الرسالة العاجلة",
    urgentMessageSending: "جاري الإرسال...",
    urgentMessageSent: "تم إرسال رسالتك بنجاح! سيتم التواصل معك قريبًا.",
    urgentMessageError: "حدث خطأ أثناء الإرسال",
    urgentMessageOptionFast: "تسريع معالجة طلب",
    urgentMessageOptionTech: "مشكلة تقنية",
    urgentMessageOptionQuestion: "استفسار عاجل",
    urgentMessageOptionOther: "أخرى",
    cmcFullName: "مدينة المهن والكفاءات",
    aiHelp: "كيف يمكنني مساعدتك؟",
    typingIndicator: "يكتب...",
    aiError: "حدث خطأ في المساعد الذكي",
    salaryDomiciliation: "شهادة تحويل الراتب غير القابلة للإلغاء",
    annualIncome: "شهادة الدخل السنوي",
    dashboardMainDesc: "لوحة التحكم الرئيسية",
    allVacationRequests: "كل طلبات الإجازة",
    allMissionOrders: "كل أوامر المهمة",
    allWorkCertificates: "كل شهادات العمل",
    quickActions: "الإجراءات السريعة",
    newVacationRequest: "طلب إجازة جديد",
    newVacationRequestDesc: "تقديم طلب إجازة سنوية أو مرضية",
    workCertificateAction: "شهادة عمل",
    workCertificateActionDesc: "طلب شهادة عمل أو راتب",
    missionOrderAction: "أمر مهمة",
    missionOrderActionDesc: "تقديم طلب أمر مهمة",
    salaryDomiciliationDesc: "طلب شهادة تحويل الراتب",
    annualIncomeDesc: "طلب شهادة الدخل السنوي",
    totalRequests: "إجمالي الطلبات",
    totalOrders: "إجمالي الأوامر",
    totalCertificates: "إجمالي الشهادات",
    allRequests: "كل الطلبات",
    notSpecified: "غير محدد",
    successTitle: "تم الإرسال بنجاح",
    successDescVacation: "تم إرسال طلب الإجازة بنجاح وسيتم معالجته قريباً",
    successDescMission: "تم إرسال طلب أمر المهمة بنجاح وسيتم معالجته قريباً",
    successDescWork: "تم إرسال طلب شهادة العمل بنجاح وسيتم معالجته قريباً",
    newRequestBtn: "إرسال طلب جديد",
    details: "تفاصيل",
    matricule: "الرقم المالي",
    status: "الحالة",
    createdAt: "تاريخ الإنشاء",
    attachment: "المرفق",
    viewFile: "عرض الملف",
    address: "العنوان",
    leaveType: "نوع الإجازة",
    duration: "المدة",
    family: "العائلة",
    direction: "الإدارة",
    grade: "الرتبة",
    echelon: "السلم",
    fonction: "الوظيفة",

    // Admin Dashboard Translations
    adminDashboardTitle: "منصة إدارة الموارد البشرية - CMC",
    adminDashboardDesc: "مركز التحكم الشامل لإدارة الموظفين والطلبات والإشعارات",
    refreshData: "تحديث البيانات",
    pendingToday: "طلبات اليوم المعلقة",
    newUsersThisWeek: "مستخدمين جدد هذا الأسبوع",
    urgentRequests: "رسائل عاجلة",
    overview: "لوحة المعلومات",
    notificationsCenter: "مركز الإشعارات",
    requestsManagement: "إدارة الطلبات",
    employeesManagement: "إدارة الموظفين",
    latestRequests: "أحدث الطلبات المقدمة",
    latestUsers: "أحدث الموظفين المسجلين",
    noRequests: "لا توجد طلبات حالياً",
    noUsers: "لا يوجد موظفون مسجلون حالياً",
    allRequestsManagement: "إدارة جميع الطلبات",
    allEmployeesManagement: "إدارة جميع الموظفين",
    pending: "معلق",
    approved: "موافق",
    rejected: "مرفوض",
    performanceMetrics: "مقاييس الأداء",
    responseRate24h: "معدل الاستجابة (24 ساعة)",
    responseRate24hDesc: "الطلبات المعالجة خلال 24 ساعة",
    avgProcessingTime: "متوسط وقت المعالجة",
    avgProcessingTimeDesc: "متوسط الوقت لإغلاق الطلب",
    rejectionRate: "معدل رفض الطلبات",
    rejectionRateDesc: "نسبة الطلبات المرفوضة من الإجمالي",
    monthlyRequests: "الطلبات الشهرية",
    monthlyRequestsDesc: "إجمالي الطلبات هذا الشهر",
    requests: "طلبات",
    employees: "موظفون",
    workCertificate_t: "شهادة عمل",
    vacationRequest_t: "طلب إجازة",
    missionOrder_t: "أمر مهمة",
    salaryDomiciliation_t: "توطين الراتب",
    annualIncome_t: "شهادة الدخل السنوي",
    urgentMessageAdminReplyTitle: "لقد تلقيت رداً من الإدارة على رسالتك العاجلة.",
    deleteRequestConfirmation: "هل أنت متأكد أنك تريد حذف هذا الطلب؟",
    delete: "حذف",
    notifApproved: "تم قبول طلبك بنجاح. سيتم تجهيز الملف قريبًا.",
    notifRejected: "تم رفض طلبك لأنه غير مكتمل أو لا يستوفي الشروط. يمكنك إعادة المحاولة بعد استكمال البيانات.",
    notifWaitingAdminFile: "تمت الموافقة على طلبك جزئيًا. انتظر ملف الإدارة.",
    notifPending: "طلبك قيد المراجعة. سيتم إعلامك عند تحديث الحالة."
  },
  fr: {
    home: "Accueil",
    dashboard: "Tableau de bord",
    pendingRequests: "Demandes en attente",
    approvedRequests: "Demandes approuvées",
    vacationDays: "Jours de congé",
    awaitingApproval: "En attente d'approbation",
    thisMonth: "Ce mois-ci",
    remaining: "Restants",
    workCertificate: "Attestation de travail",
    missionOrder: "Ordre de mission",
    vacationRequest: "Demande de congé",
    settings: "Paramètres",
    profile: "Profil",
    notifications: "Notifications",
    logout: "Déconnexion",
    search: "Rechercher",
    viewAll: "Voir tout",
    name: "Nom",
    startDate: "Date de début",
    endDate: "Date de fin",
    submit: "Envoyer la demande",
    cancel: "Annuler",
    signatureUpload: "Télécharger la signature",
    reason: "Raison",
    type: "Type",
    description: "Description",
    save: "Enregistrer",
    requestType: "Type de demande",
    workCertificateTitle: "Demande d'attestation de travail",
    missionOrderTitle: "Demande d'ordre de mission",
    vacationRequestTitle: "Demande de congé",
    purposeLabel: "Objectif de la demande",
    purposePlaceholder: "Par exemple: Soumission à la banque, visa de voyage, etc.",
    additionalInfo: "Informations supplémentaires",
    additionalInfoPlaceholder: "Toute information supplémentaire que vous souhaitez ajouter à la demande",
    signatureUploadButton: "Choisir le fichier de signature",
    requestSubmitted: "Votre demande a été soumise avec succès !",
    requestReviewMessage: "La demande sera examinée et le certificat sera délivré dans les plus brefs délais",
    followUpMessage: "Vous pouvez suivre le statut de votre demande depuis la page d'accueil",
    newRequest: "Nouvelle demande",
    requestInfo: "Informations sur la demande",
    destination: "Destination",
    destinationPlaceholder: "Par exemple:Casablanca, Rabat, à l'étranger",
    selectDate: "Sélectionner une date",
    signature: "Signature",
    annualLeave: "Congé annuel",
    sickLeave: "Congé maladie",
    emergencyLeave: "Congé d'urgence",
    unpaidLeave: "Congé sans solde",
    vacationReasonPlaceholder: "Veuillez indiquer la raison du congé si nécessaire",
    profileSettings: "Informations du profil",
    email: "E-mail",
    phone: "Téléphone",
    saveChanges: "Enregistrer les modifications",
    notificationSettings: "Paramètres de notification",
    emailNotifications: "Notifications par e-mail",
    emailNotificationsDesc: "Recevoir des notifications par e-mail",
    newRequests: "Nouvelles demandes",
    newRequestsDesc: "Notifications lors de la création de nouvelles demandes",
    requestUpdates: "Mises à jour des demandes",
    requestUpdatesDesc: "Notifications lors de la mise à jour du statut des demandes",
    passwordSettings: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    changePassword: "Changer le mot de passe",
    profileTab: "Profil",
    notificationsTab: "Notifications",
    passwordTab: "Mot de passe",
    urgentChat: "Chat urgent",
    urgentMessageTitle: "Message urgent à l'administration",
    urgentMessagePlaceholder: "Écrivez votre message urgent ici...",
    urgentMessageSend: "Envoyer le message urgent",
    urgentMessageSending: "Envoi en cours...",
    urgentMessageSent: "Votre message a été envoyé avec succès ! Nous vous contacterons bientôt.",
    urgentMessageError: "Une erreur s'est produite lors de l'envoi",
    urgentMessageOptionFast: "Accélérer le traitement d'une demande",
    urgentMessageOptionTech: "Problème technique",
    urgentMessageOptionQuestion: "Question urgente",
    urgentMessageOptionOther: "Autre",
    aiAssistant: "Assistant CMC",
    cmcFullName: "Cité des Métiers et des Compétences",
    aiHelp: "Comment puis-je vous aider?",
    typingIndicator: "Tape...",
    salaryDomiciliation: "Attestation de domiciliation irrévocable de salaire",
    annualIncome: "Attestation de revenus annuels",
    dashboardMainDesc: "Tableau de bord principal",
    allVacationRequests: "Toutes les demandes de congé",
    allMissionOrders: "Tous les ordres de mission",
    allWorkCertificates: "Toutes les attestations de travail",
    quickActions: "Actions rapides",
    newVacationRequest: "Nouvelle demande de congé",
    newVacationRequestDesc: "Soumettre une demande de congé annuel ou maladie",
    workCertificateAction: "Attestation de travail",
    workCertificateActionDesc: "Demander une attestation de travail ou de salaire",
    missionOrderAction: "Ordre de mission",
    missionOrderActionDesc: "Soumettre une demande d'ordre de mission",
    salaryDomiciliationDesc: "Demander une attestation de domiciliation de salaire",
    annualIncomeDesc: "Demander une attestation de revenus annuels",
    totalRequests: "Total des demandes",
    totalOrders: "Total des ordres",
    totalCertificates: "Total des attestations",
    allRequests: "Toutes les demandes",
    notSpecified: "Non spécifié",
    successTitle: "Envoyé avec succès",
    successDescVacation: "Votre demande de congé a été envoyée avec succès et sera traitée prochainement.",
    successDescMission: "Votre demande d'ordre de mission a été envoyée avec succès et sera traitée prochainement.",
    successDescWork: "Votre demande d'attestation de travail a été envoyée avec succès et sera traitée prochainement.",
    newRequestBtn: "Nouvelle demande",
    details: "Détails",
    matricule: "Matricule",
    status: "Statut",
    createdAt: "Date de création",
    attachment: "Pièce jointe",
    viewFile: "Voir le fichier",
    address: "Adresse",
    leaveType: "Type de congé",
    duration: "Durée",
    family: "Famille",
    direction: "Direction",
    grade: "Grade",
    echelon: "Échelon",
    fonction: "Fonction",

    // Admin Dashboard Translations
    adminDashboardTitle: "Plateforme de Gestion RH - CMC",
    adminDashboardDesc: "Centre de contrôle complet pour la gestion des employés, des demandes et des notifications",
    refreshData: "Actualiser les données",
    pendingToday: "Demandes en attente aujourd'hui",
    newUsersThisWeek: "Nouveaux utilisateurs cette semaine",
    urgentRequests: "Messages urgents",
    overview: "Tableau de bord",
    notificationsCenter: "Centre de notifications",
    requestsManagement: "Gestion des demandes",
    employeesManagement: "Gestion des employés",
    latestRequests: "Dernières demandes soumises",
    latestUsers: "Derniers employés inscrits",
    noRequests: "Aucune demande pour le moment",
    noUsers: "Aucun employé inscrit pour le moment",
    allRequestsManagement: "Gestion de toutes les demandes",
    allEmployeesManagement: "Gestion de tous les employés",
    pending: "En attente",
    approved: "Approuvée",
    rejected: "Rejetée",
    performanceMetrics: "Indicateurs de performance",
    responseRate24h: "Taux de réponse (24h)",
    responseRate24hDesc: "Demandes traitées en 24 heures",
    avgProcessingTime: "Temps de traitement moyen",
    avgProcessingTimeDesc: "Temps moyen pour clore une demande",
    rejectionRate: "Taux de rejet",
    rejectionRateDesc: "Pourcentage de demandes rejetées",
    monthlyRequests: "Demandes mensuelles",
    monthlyRequestsDesc: "Total des demandes ce mois-ci",
    requests: "Demandes",
    employees: "Employés",
    workCertificate_t: "Attestation de travail",
    vacationRequest_t: "Demande de congé",
    missionOrder_t: "Ordre de mission",
    salaryDomiciliation_t: "Domiciliation de salaire",
    annualIncome_t: "Attestation de revenu annuel",
    urgentMessageAdminReplyTitle: "Vous avez reçu une réponse de l'administration à votre demande urgente.",
    deleteRequestConfirmation: "Êtes-vous sûr de vouloir supprimer cette demande ?",
    delete: "Supprimer",
    notifApproved: "Votre demande a été acceptée. Le fichier sera prêt bientôt.",
    notifRejected: "Votre demande a été rejetée car elle est incomplète ou ne répond pas aux critères. Vous pouvez réessayer après avoir complété les informations.",
    notifWaitingAdminFile: "Votre demande a été partiellement acceptée. Attendez le fichier de l'admin.",
    notifPending: "Votre demande est en cours de traitement. Vous serez notifié lors de la mise à jour."
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className="min-h-screen">
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
